OnlineAlbum/OnlineAlbum/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineAlbum.Models;

namespace OnlineAlbum.Controllers
{

    [Authorize]
    public class FriendsController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Followers
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult SearchPeople(string name)
        {
            if(name == null)
            {
                return RedirectToAction("Index");
            }
            
            var searching = db.UserProfiles.Where(u => u.UserName == name);

            return PartialView(searching.FirstOrDefault());
        }

        public ActionResult SubscribeMenu(string name)
        {
            var friendList = UserFriendList(name);

            if (db.UserProfiles.Where( n => n.UserName == name).Any() && name != User.Identity.Name)
            {
                if (friendList.Where(n => n.FriendName == name).Any())
                {
                    return PartialView("_UnSubscribe", name);
                }
                else
                {
                    return PartialView("_Subscribe", name);
                }  
            }
            return PartialView();
        }

       
        public ActionResult Subscribe(string name)
        {
            var subscribe = UserFriendList(name);

            subscribe.
                Add(new FriendList()
                    {
                        FriendName = name
                    });
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    
        public ActionResult UnSubscribe(string name)
        {
            var friend = db.FriendList.Where(n => n.FriendName == name).First();
            db.FriendList.Remove(friend);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        private List<FriendList> UserFriendList(string name)
        {
            var subscribe = db.UserProfiles.
            Where(u => u.UserName == User.Identity.Name).
                First().
                    FriendList;
            return (subscribe);
        }
    }
}

OnlineAlbum/OnlineAlbum/Views/Friends/Index.cshtml
@model OnlineAlbum.Models.UserProfile
@{
    ViewBag.Title = "Add Friend";

    var options = new AjaxOptions()
    {
        UpdateTargetId = "UpdateData",
        LoadingElementId = "Loading"
    };
}

@using (Ajax.BeginForm("SearchPeople", options))
{
    <div class="search">
        <h2>Find Friend</h2>
        <input type="text" name="Name" placeholder="Search..." class="input-sm" />
        <button type="submit" class="btn btn-default">Search</button>
    </div>
}

<div id="UpdateData">
    <img id="Loading" src="~/Content/spinner.gif" style="display:none;" />
</div>

@section scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

OnlineAlbum/OnlineAlbum/Views/Friends/SearchPeople.cshtml
@model OnlineAlbum.Models.UserProfile

@{ 
    var options = new AjaxOptions()
    {
        UpdateTargetId = "AddFriendButton",
        HttpMethod = "Post"
    };
}

@if (Model != null)
{
    <div>
            @using (Ajax.BeginForm("SubscribeMenu", options))
            {
                <img src="~/Content/UserAvatar.png" style="height:60px" />
                @Model.UserName
                <div id="AddFriendButton">
                    @Html.Action("SubscribeMenu", new { name = Model.UserName })
                </div>
            }
    </div>
}else{ 
    <span>
        No match allowed
    </span>
 }

OnlineAlbum/OnlineAlbum/Views/Friends/SubscribeMenu.cshtml
<button class="btn btn-success" disabled="disabled">
    Subscribe
</button>

OnlineAlbum/OnlineAlbum/Views/Friends/_Subscribe.cshtml
@model string

@Html.ActionLink("Subscribe", "Subscribe", "Friends", new { name = Model }, new { @class = "btn btn-success", FormMethod.Post })

OnlineAlbum/OnlineAlbum/Views/Friends/_UnSubscribe.cshtml
@model string

@Html.ActionLink("UnSubscribe", "UnSubscribe", "Friends", new { name = Model }, new { @class = "btn btn-danger", FormMethod.Post })